#!/usr/bin/env python3

# Copyright 2022 Canonical Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
import subprocess
from argparse import ArgumentParser

PORT = 2049
HOSTNAME = subprocess.check_output(
    "hostname",
    shell=True
).decode().strip("\n")

CHECK_TCP = "/usr/lib/nagios/plugins/check_tcp -H {} -p {}"

SERVICE_STATUS = {
    0: "OKAY",
    1: "WARNING",
    2: "CRITICAL",
    3: "UNKNOWN",
}

def main(args):
    exit_code = 0
    message = ""
    try:
        output = subprocess.check_output(
            CHECK_TCP.format(args.domain, args.port),
            stderr = subprocess.STDOUT,
            shell = True,
        ).decode().strip()
        message = output
    except subprocess.CalledProcessError as e:
        exit_code = e.returncode
        message = e.stdout
    except Exception as e:
        exit_code = 3
        message = e

    print(f"NFS service {SERVICE_STATUS[exit_code]}: {message}")
    sys.exit(exit_code)

def parse_cli():
    parser = ArgumentParser()
    parser.add_argument(
        "--domain",
        type=str,
        default=HOSTNAME,
        help="Set the NFS domain.",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=PORT,
        help="Set the NFS port.",
    )

    return parser.parse_args()

if __name__ == "__main__":
    args = parse_cli()
    main(args)
